version: "3"

services:
  django:
    build: ./backend
    container_name: klav_django
    expose:
      - "8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db

  websocket:
    build: ./websocket
    container_name: klav_websocket
    expose:
      - "5001"
    env_file:
      - .env
    restart: always

  db:
    image: postgres:15
    container_name: klav_postgres
    environment:
      POSTGRES_DB: klav
      POSTGRES_USER: klav
      POSTGRES_PASSWORD: klav
    ports:
      - "5432:5432"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: klav_nginx
    ports:
      - "5000:5000"   # 외부 → nginx → 내부 라우팅
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
      - websocket
    restart: always
